version: "2"
services:
    backend:
        nginx: "./nginx"
        container_name: "nginx"
        environment:
            - TZ=Asia/Bangkok
        volumes:
            - "./code:/usr/share/code"
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./php/run:/run/php"
        ports:
            - 8080:80
        working_dir: "/usr/share/code"
        links:
            - php
        network_mode: "bridge"
        restart: always
    php:
        build: "./php"
        container_name: "php"
        volumes:
            - "./code:/usr/share/code"
            - "./php/run:/run/php"
        working_dir: "/usr/share/code"
        environment:
           - "TZ=Asia/Bangkok"
        network_mode: "bridge"
        restart: always
    # redis:
    #     build: "./redis"
    #     container_name: "redis"
    #     ports:
    #         - "6379:6379"
    #     network_mode: "bridge"
    #     restart: always